server:
  port: 10010

mybatis:
  mapper-locations: classpath:/mapper/*.xml

spring:
  application:
    name: myFootball
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
